name: Terraform Apply

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"
      - ".github/workflows/terraform-plan.yml"
      - ".github/workflows/terraform-apply.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::387219500605:role/maintenance-darkmira-dev-github-actions-terraform
          role-session-name: gh-terraform-apply
          aws-region: eu-north-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform Apply
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
        run: terraform apply -input=false -auto-approve tfplan
